// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protobuf/brand.proto

package golang_protobuf_brand

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoBrandRepo struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Brands        []*ProtoBrandRepo_ProtoBrand `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoBrandRepo) Reset() {
	*x = ProtoBrandRepo{}
	mi := &file_protobuf_brand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoBrandRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBrandRepo) ProtoMessage() {}

func (x *ProtoBrandRepo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_brand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBrandRepo.ProtoReflect.Descriptor instead.
func (*ProtoBrandRepo) Descriptor() ([]byte, []int) {
	return file_protobuf_brand_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoBrandRepo) GetBrands() []*ProtoBrandRepo_ProtoBrand {
	if x != nil {
		return x.Brands
	}
	return nil
}

type ProtoBrandRepo_ProtoBrand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            uint64                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Year          uint32                 `protobuf:"varint,3,opt,name=Year,proto3" json:"Year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoBrandRepo_ProtoBrand) Reset() {
	*x = ProtoBrandRepo_ProtoBrand{}
	mi := &file_protobuf_brand_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoBrandRepo_ProtoBrand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBrandRepo_ProtoBrand) ProtoMessage() {}

func (x *ProtoBrandRepo_ProtoBrand) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_brand_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBrandRepo_ProtoBrand.ProtoReflect.Descriptor instead.
func (*ProtoBrandRepo_ProtoBrand) Descriptor() ([]byte, []int) {
	return file_protobuf_brand_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProtoBrandRepo_ProtoBrand) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ProtoBrandRepo_ProtoBrand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtoBrandRepo_ProtoBrand) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

var File_protobuf_brand_proto protoreflect.FileDescriptor

const file_protobuf_brand_proto_rawDesc = "" +
	"\n" +
	"\x14protobuf/brand.proto\x12\x15golang_protobuf_brand\"\xa0\x01\n" +
	"\x0eProtoBrandRepo\x12H\n" +
	"\x06brands\x18\x01 \x03(\v20.golang_protobuf_brand.ProtoBrandRepo.ProtoBrandR\x06brands\x1aD\n" +
	"\n" +
	"ProtoBrand\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x04R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Year\x18\x03 \x01(\rR\x04YearB\x18Z\x16/golang_protobuf_brandb\x06proto3"

var (
	file_protobuf_brand_proto_rawDescOnce sync.Once
	file_protobuf_brand_proto_rawDescData []byte
)

func file_protobuf_brand_proto_rawDescGZIP() []byte {
	file_protobuf_brand_proto_rawDescOnce.Do(func() {
		file_protobuf_brand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_brand_proto_rawDesc), len(file_protobuf_brand_proto_rawDesc)))
	})
	return file_protobuf_brand_proto_rawDescData
}

var file_protobuf_brand_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_brand_proto_goTypes = []any{
	(*ProtoBrandRepo)(nil),            // 0: golang_protobuf_brand.ProtoBrandRepo
	(*ProtoBrandRepo_ProtoBrand)(nil), // 1: golang_protobuf_brand.ProtoBrandRepo.ProtoBrand
}
var file_protobuf_brand_proto_depIdxs = []int32{
	1, // 0: golang_protobuf_brand.ProtoBrandRepo.brands:type_name -> golang_protobuf_brand.ProtoBrandRepo.ProtoBrand
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_brand_proto_init() }
func file_protobuf_brand_proto_init() {
	if File_protobuf_brand_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_brand_proto_rawDesc), len(file_protobuf_brand_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_brand_proto_goTypes,
		DependencyIndexes: file_protobuf_brand_proto_depIdxs,
		MessageInfos:      file_protobuf_brand_proto_msgTypes,
	}.Build()
	File_protobuf_brand_proto = out.File
	file_protobuf_brand_proto_goTypes = nil
	file_protobuf_brand_proto_depIdxs = nil
}
